# Generated by Django 2.0.2 on 2018-03-02 12:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('meta_title', models.CharField(max_length=45, blank=True, null=True)),
                ('meta_description', models.CharField(max_length=255, blank=True, null=True)),
                ('meta_keywords', models.CharField(max_length=255, blank=True, null=True)),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_update', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('text', models.TextField()),
                ('meta_title', models.CharField(max_length=45, blank=True, null=True)),
                ('meta_description', models.CharField(max_length=255, blank=True, null=True)),
                ('meta_keywords', models.CharField(max_length=255, blank=True, null=True)),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_update', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255, unique=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handmade.Gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('short_text', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('meta_title', models.CharField(max_length=45, blank=True, null=True)),
                ('meta_description', models.CharField(max_length=255, blank=True, null=True)),
                ('meta_keywords', models.CharField(max_length=255, blank=True, null=True)),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_update', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
